name: example
description: Demonstrates how to use the adaptive_scroller package.
publish_to: 'none' # Prevent this example from being published

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Add a dependency on your library. The `path: ../` tells Flutter to
  # use the library code from the parent directory, not from pub.dev.
  adaptive_scroller:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
